import { NextRequest, NextResponse } from "next/server";
import { checkRateLimit, getClientIp, tooManyRequestsResponse } from "@/app/lib/rateLimit";
import { callClaudeMessages } from "@/app/lib/ai/anthropic";
import { CLINICAL_AI_GUARDRAILS } from "@/app/lib/ai/clinicalGuardrails";
import { connectDB } from "@/app/lib/mongodb";
import { getSettings } from "@/app/models/Settings";

// Public, unauthenticated — like app/api/journey-simulator, this hits a paid
// AI API with no auth wall, so it's rate-limited per IP rather than sitting
// behind requirePermission like the admin-side AI routes.
const MAX_MESSAGES = 20;
const MAX_MESSAGE_LENGTH = 300;

export async function POST(req: NextRequest) {
  const ip = getClientIp(req);
  const rl = checkRateLimit(`assessment-chat:${ip}`, 20, 60 * 60 * 1000);
  if (!rl.allowed) return tooManyRequestsResponse(rl.resetAt);

  if (!process.env.ANTHROPIC_API_KEY) {
    return NextResponse.json({ success: false, message: "AI not configured" }, { status: 503 });
  }

  try {
    const { messages, context } = await req.json();
    if (!Array.isArray(messages) || messages.length === 0) {
      return NextResponse.json({ success: false, message: "messages is required" }, { status: 400 });
    }
    if (messages.length > MAX_MESSAGES) {
      return NextResponse.json({ success: false, message: "Conversation too long — please book a consultation to continue." }, { status: 400 });
    }

    const cleanMessages = messages
      .filter((m: any) => m && (m.role === "user" || m.role === "assistant") && typeof m.content === "string")
      .map((m: any) => ({ role: m.role, content: m.content.slice(0, MAX_MESSAGE_LENGTH) }));
    if (cleanMessages.length === 0 || cleanMessages[cleanMessages.length - 1].role !== "user") {
      return NextResponse.json({ success: false, message: "Invalid message history" }, { status: 400 });
    }

    const primaryConcern = typeof context?.primaryConcern === "string" ? context.primaryConcern.slice(0, 100) : "";
    const doctorMessage = typeof context?.doctorMessage === "string" ? context.doctorMessage.slice(0, 500) : "";
    const rawRecommendations = Array.isArray(context?.recommendations) ? context.recommendations.slice(0, 3) : [];

    // Untrusted client input feeds straight into the system prompt below, so
    // every field is coerced to the expected type (never trusted as-is) —
    // otherwise a malformed/hostile payload can crash the route (e.g. a
    // string where an array is expected) or inject arbitrary text into the
    // assistant's persona context.
    const str = (v: any, max: number) => (typeof v === "string" ? v.slice(0, max) : "");
    const strArray = (v: any, max: number) => (Array.isArray(v) ? v.filter((x) => typeof x === "string").slice(0, 5).map((x) => x.slice(0, max)) : []);
    const recommendations = rawRecommendations.map((t: any) => ({
      name: str(t?.name, 100) || "Unknown",
      confidence: typeof t?.confidence === "number" ? Math.max(0, Math.min(100, t.confidence)) : undefined,
      description: str(t?.description, 300),
      sessions: str(t?.sessions, 100),
      duration: str(t?.duration, 100),
      recovery: str(t?.recovery, 100),
      price: str(t?.price, 100),
      advantages: strArray(t?.advantages, 150),
      disadvantages: strArray(t?.disadvantages, 150),
    }));

    const treatmentContext = recommendations
      .map((t, i: number) =>
        `${i + 1}. ${t.name} (${t.confidence ?? "?"}% match) — ${t.description}. Sessions: ${t.sessions || "N/A"}. Duration: ${t.duration || "N/A"}. Recovery: ${t.recovery || "N/A"}. Price: ${t.price || "N/A"}.${t.advantages.length ? ` Advantages: ${t.advantages.join(", ")}.` : ""}${t.disadvantages.length ? ` Considerations: ${t.disadvantages.join(", ")}.` : ""}`
      )
      .join("\n");

    await connectDB();
    const settings = await getSettings();
    const clinicName = settings.clinicProfile?.name || "DR Youth Clinic";
    const clinicCountry = settings.clinicProfile?.country || "India";

    const systemPrompt = `${CLINICAL_AI_GUARDRAILS}

You are a patient-education assistant for ${clinicName}, a dermatology and aesthetic clinic in ${clinicCountry}.

A patient just completed a clinical intake. Their main concern: "${primaryConcern || "not specified"}".

Their possible discussion topics (already generated by the clinic's intake engine — do not invent new treatments, only discuss these or general, safe educational context):
${treatmentContext || "No specific topics matched yet."}

${doctorMessage ? `Doctor's general note shown to the patient: "${doctorMessage}"` : ""}

Rules:
- Answer ONLY using the treatment info above plus safe, general educational knowledge about these exact treatments.
- Never quote a price/session count different from what's given above.
- If asked something outside this scope (unrelated medical advice, other conditions, anything requiring an in-person exam), say a doctor can address that at consultation and suggest booking.
- Keep answers to 2-4 short sentences, friendly and clear, no medical jargon without explaining it.
- End with a brief nudge toward booking a free consultation when it's a natural fit, but not on every single reply.`;

    const reply = await callClaudeMessages({ system: systemPrompt, messages: cleanMessages, maxTokens: 400 });

    return NextResponse.json({ success: true, data: { reply } });
  } catch (err: any) {
    return NextResponse.json({ success: false, message: err.message || "Chat failed" }, { status: 500 });
  }
}
