import { NextRequest, NextResponse } from "next/server";
import { checkRateLimit, getClientIp, tooManyRequestsResponse } from "@/app/lib/rateLimit";

// Public, unauthenticated — like app/api/journey-simulator, this hits a paid
// AI API with no auth wall, so it's rate-limited per IP rather than sitting
// behind requirePermission like the admin-side AI routes.
const MAX_MESSAGES = 20;
const MAX_MESSAGE_LENGTH = 300;

export async function POST(req: NextRequest) {
  const ip = getClientIp(req);
  const rl = checkRateLimit(`assessment-chat:${ip}`, 20, 60 * 60 * 1000);
  if (!rl.allowed) return tooManyRequestsResponse(rl.resetAt);

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return NextResponse.json({ success: false, message: "AI not configured" }, { status: 503 });
  }

  try {
    const { messages, context } = await req.json();
    if (!Array.isArray(messages) || messages.length === 0) {
      return NextResponse.json({ success: false, message: "messages is required" }, { status: 400 });
    }
    if (messages.length > MAX_MESSAGES) {
      return NextResponse.json({ success: false, message: "Conversation too long — please book a consultation to continue." }, { status: 400 });
    }

    const cleanMessages = messages
      .filter((m: any) => m && (m.role === "user" || m.role === "assistant") && typeof m.content === "string")
      .map((m: any) => ({ role: m.role, content: m.content.slice(0, MAX_MESSAGE_LENGTH) }));
    if (cleanMessages.length === 0 || cleanMessages[cleanMessages.length - 1].role !== "user") {
      return NextResponse.json({ success: false, message: "Invalid message history" }, { status: 400 });
    }

    const primaryConcern = typeof context?.primaryConcern === "string" ? context.primaryConcern.slice(0, 100) : "";
    const doctorMessage = typeof context?.doctorMessage === "string" ? context.doctorMessage.slice(0, 500) : "";
    const rawRecommendations = Array.isArray(context?.recommendations) ? context.recommendations.slice(0, 3) : [];

    // Untrusted client input feeds straight into the system prompt below, so
    // every field is coerced to the expected type (never trusted as-is) —
    // otherwise a malformed/hostile payload can crash the route (e.g. a
    // string where an array is expected) or inject arbitrary text into the
    // assistant's persona context.
    const str = (v: any, max: number) => (typeof v === "string" ? v.slice(0, max) : "");
    const strArray = (v: any, max: number) => (Array.isArray(v) ? v.filter((x) => typeof x === "string").slice(0, 5).map((x) => x.slice(0, max)) : []);
    const recommendations = rawRecommendations.map((t: any) => ({
      name: str(t?.name, 100) || "Unknown",
      confidence: typeof t?.confidence === "number" ? Math.max(0, Math.min(100, t.confidence)) : undefined,
      description: str(t?.description, 300),
      sessions: str(t?.sessions, 100),
      duration: str(t?.duration, 100),
      recovery: str(t?.recovery, 100),
      price: str(t?.price, 100),
      advantages: strArray(t?.advantages, 150),
      disadvantages: strArray(t?.disadvantages, 150),
    }));

    const treatmentContext = recommendations
      .map((t, i: number) =>
        `${i + 1}. ${t.name} (${t.confidence ?? "?"}% match) — ${t.description}. Sessions: ${t.sessions || "N/A"}. Duration: ${t.duration || "N/A"}. Recovery: ${t.recovery || "N/A"}. Price: ${t.price || "N/A"}.${t.advantages.length ? ` Advantages: ${t.advantages.join(", ")}.` : ""}${t.disadvantages.length ? ` Considerations: ${t.disadvantages.join(", ")}.` : ""}`
      )
      .join("\n");

    const systemPrompt = `You are a patient-education assistant for DR Youth Clinic, a dermatology and aesthetic clinic in India. You are NOT a doctor and must not make diagnoses, medical guarantees, or promise specific results.

A patient just completed an AI skin & hair assessment. Their main concern: "${primaryConcern || "not specified"}".

Their matched treatments (already generated by the clinic's assessment engine — do not invent new treatments, only discuss these or general, safe educational context):
${treatmentContext || "No specific treatments matched yet."}

${doctorMessage ? `Doctor's general note shown to the patient: "${doctorMessage}"` : ""}

Rules:
- Answer ONLY using the treatment info above plus safe, general educational knowledge about these exact treatments.
- Never diagnose, never guarantee results, never quote a price/session count different from what's given above.
- If asked something outside this scope (unrelated medical advice, other conditions, anything requiring an in-person exam), say a doctor can address that at consultation and suggest booking.
- Keep answers to 2-4 short sentences, friendly and clear, no medical jargon without explaining it.
- End with a brief nudge toward booking a free consultation when it's a natural fit, but not on every single reply.`;

    const response = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
      },
      body: JSON.stringify({
        model: "claude-haiku-4-5-20251001",
        max_tokens: 400,
        system: systemPrompt,
        messages: cleanMessages,
      }),
    });

    if (!response.ok) throw new Error(`AI API error: ${response.status}`);

    const data = await response.json();
    const reply = (data.content?.[0]?.text ?? "").trim();
    if (!reply) throw new Error("Empty AI response");

    return NextResponse.json({ success: true, data: { reply } });
  } catch (err: any) {
    return NextResponse.json({ success: false, message: err.message || "Chat failed" }, { status: 500 });
  }
}
