import { createHash } from "crypto";
import { NextRequest, NextResponse } from "next/server";
import { connectDB } from "@/app/lib/mongodb";
import { getAdminUser } from "@/app/lib/adminAuth";
import Booking from "@/app/models/Booking";
import ExportToken from "@/app/models/ExportToken";
import { EXPORT_FIELDS_BY_ROLE, type AdminRole } from "@/app/lib/permissions";

export const dynamic = "force-dynamic";

const FIELD_HEADERS: Record<string, string> = {
  bookingId:     "Booking ID",
  name:          "Patient Name",
  phone:         "Phone",
  service:       "Service",
  location:      "Branch",
  date:          "Appointment Date",
  time:          "Appointment Time",
  status:        "Status",
  concern:       "Concern",
  promoCode:     "Promo Code",
  promoDiscount: "Promo Discount",
  createdAt:     "Lead Date",
};

function escapeCell(value: unknown): string {
  const text = value instanceof Date
    ? value.toLocaleDateString("en-IN", { day: "2-digit", month: "2-digit", year: "numeric" }) + " " +
      value.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit", hour12: true })
    : String(value ?? "");
  // Prefix formula-injection characters to prevent CSV injection
  const safe = /^[=+\-@\t\r]/.test(text) ? `'${text}` : text;
  return /[",\n\r]/.test(safe) ? `"${safe.replace(/"/g, '""')}"` : safe;
}

function buildRow(doc: Record<string, any>, fields: string[]): string {
  return fields.map((f) => escapeCell(doc[f])).join(",");
}

function buildQuery(
  filters: { dateFrom?: string; dateTo?: string; location?: string; status?: string; service?: string },
  assignedClinics: string[]
): Record<string, any> {
  const q: Record<string, any> = {};

  const branchRestricted = !assignedClinics.includes("all");
  if (branchRestricted) {
    q.location = { $in: assignedClinics };
  } else if (filters.location) {
    q.location = filters.location;
  }

  if (filters.status)  q.status  = filters.status;
  if (filters.service) q.service = { $regex: filters.service, $options: "i" };

  if (filters.dateFrom || filters.dateTo) {
    q.createdAt = {};
    if (filters.dateFrom) q.createdAt.$gte = new Date(filters.dateFrom);
    if (filters.dateTo)   q.createdAt.$lte = new Date(filters.dateTo + "T23:59:59.999Z");
  }

  return q;
}

export async function GET(
  req: NextRequest,
  { params }: { params: { token: string } }
) {
  await connectDB();

  const user = await getAdminUser();
  if (!user) {
    return NextResponse.json({ success: false, message: "Unauthorized" }, { status: 401 });
  }

  const rawToken  = params.token;
  const tokenHash = createHash("sha256").update(rawToken).digest("hex");

  const record = await (ExportToken as any).findOne({ tokenHash }).lean() as any;

  if (!record) {
    return NextResponse.json({ success: false, message: "Download link is invalid or has expired." }, { status: 404 });
  }
  if (new Date() > new Date(record.expiresAt)) {
    return NextResponse.json({ success: false, message: "Download link has expired." }, { status: 410 });
  }
  if (record.usedAt) {
    return NextResponse.json({ success: false, message: "This download link has already been used." }, { status: 410 });
  }
  if (String(record.adminUserId) !== String(user._id)) {
    return NextResponse.json({ success: false, message: "This download link belongs to a different user." }, { status: 403 });
  }

  // Mark token as used immediately (one-time enforcement)
  await (ExportToken as any).findByIdAndUpdate(record._id, { $set: { usedAt: new Date() } });

  const fields  = EXPORT_FIELDS_BY_ROLE[user.role as AdminRole] ?? [];
  if (fields.length === 0) {
    return NextResponse.json({ success: false, message: "Your role does not have permission to export lead data." }, { status: 403 });
  }

  const query   = buildQuery(record.filters ?? {}, user.assignedClinics);
  const records = await (Booking as any).find(query).sort({ createdAt: -1 }).limit(500).lean() as any[];

  // Build watermark rows
  const now       = new Date();
  const dateStr   = now.toLocaleDateString("en-IN", { day: "2-digit", month: "2-digit", year: "numeric" });
  const timeStr   = now.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: true });
  const branchStr = user.assignedClinics.includes("all")
    ? (record.filters?.location || "All Branches")
    : user.assignedClinics.join(", ");
  const ip        = req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || "unknown";

  const watermark = [
    "DR YOUTH CLINIC — CONFIDENTIAL PATIENT LEAD EXPORT",
    `Exported By:,${user.name}`,
    `Email:,${user.email}`,
    `Role:,${user.role}`,
    `Export Date:,${dateStr}`,
    `Export Time:,${timeStr}`,
    `Branch:,${branchStr}`,
    `IP Address:,${ip}`,
    `Total Records:,${records.length}`,
    "Generated By:,DR Youth CRM System",
    "WARNING:,This file contains confidential patient information. Unauthorized distribution is prohibited.",
    "",
  ].join("\n");

  const headers  = fields.map((f) => FIELD_HEADERS[f] ?? f).join(",");
  const dataRows = records.map((doc: any) => buildRow(doc, fields)).join("\n");

  // BOM ensures Excel opens UTF-8 CSV correctly
  const csv = "﻿" + watermark + headers + "\n" + dataRows + "\n";

  const filename = `leads_export_${dateStr.replace(/\//g, "-")}_${Date.now()}.csv`;

  return new NextResponse(csv, {
    status: 200,
    headers: {
      "Content-Type":        "text/csv; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Cache-Control":       "no-store, no-cache, must-revalidate",
      "Pragma":              "no-cache",
      "X-Content-Type-Options": "nosniff",
    },
  });
}
